### ISSUE TITLE
media-libs/avidemux-plugins-2.6.20 - configure time error

### ISSUE THREAD

**Issue by stefantalpalaru** [bobwya/bobwya#15]
```
-- Checking for x264
-- *****************
-- Found x264.h
--   core version: 152
-- Found x264.h
-- Found x264 library
-- Found x264_encoder_open_152 in /usr/lib/libx264.so
CMake Error at /usr/include/avidemux/2.6/cmake/admCheckX264.cmake:24 (ELSE):
  A duplicate ELSE command was found inside an IF block.
Call Stack (most recent call first):
  ADM_videoEncoder/x264/CMakeLists.txt:12 (checkX264)
```

CMake version: 3.9.0

**Comment by bobwya** [comment]
I may not get a chance to look at this till Monday 24 July - as I'm working long hours all weekend :-(
Just to warn you!

I gather from the **#gentoo-kde** that **CMake 3.9.0** has some parallel build "issues"...

**Comment by bobwya** [comment]
@Ștefan,

OK should be fixed - it's just an Upstream syntax error in the **X264** library checking cmake file (which earlier version of **cmake** just ignore).
I've backported the Upstream patch to all previous versions of this package. See: [[cmake/x264] Fix build with cmake 3.9.0](https://github.com/mean00/avidemux2/commit/c5edc6cf7b3768ac1409c6cef69ab5980a86596a).

Please test and report if the package builds now... Then we can close this Issue!

Ta
Bob

**Comment by stefantalpalaru** [comment]
No luck. Maybe you're supposed to also apply that patch to avidemux-core, because that's where the used file comes from.

**Comment by bobwya** [comment]
Righteo, I've updated my system to **cmake 3.9.0**.
Put the patch into **avidemux-core** and a package warning - if the system **cmake** is >=**3.9.0**.
Build (/run) tests are a go here - so I'm closing the bug... :-)
Please comment if you have any further issues!

**Comment by stefantalpalaru** [comment]
All good.

**Comment by bobwya** [comment]
Cool :-)
