### ISSUE TITLE
freetype 2.8.1 breaks Wine build during font conversion with sfnt2fon

### ISSUE THREAD

**Issue by stefantalpalaru** [bobwya/bobwya#17]
```[ebuild     U  ] app-emulation/wine-2.17-r1::bobwya [2.16-r1::bobwya] USE="X alsa cuda cups gecko jpeg lcms mono mp3 ncurses nls opencl opengl perl png realtime run-exes ssl staging threads truetype udev udisks xcomposite xml -capi -custom-cflags -dos -fontconfig -gphoto2 -gsm -gstreamer -ldap -netapi -odbc -openal -osmesa -oss -pcap -pipelight -prelink -pulseaudio -s3tc -samba -scanner (-selinux) {-test} -themes -v4l -vaapi -vulkan -xinerama" ABI_X86="32 64 (-x32)" LINGUAS="en -ar -bg -ca -cs -da -de -el -en_US -eo -es -fa -fi -fr -he -hi -hr -hu -it -ja -ko -lt -ml -nb_NO -nl -or -pa -pl -pt_BR -pt_PT -rm -ro -ru -sk -sl -sr_RS@cyrillic -sr_RS@latin -sv -te -th -tr -uk -wa -zh_CN -zh_TW" 0 KiB```

Error message:
```
make[1]: Entering directory '/var/tmp/portage/app-emulation/wine-2.17-r1/work/wine-2.17-abi_x86_32.x86/fonts'
../tools/sfnt2fon/sfnt2fon -o coue1255.fon /var/tmp/portage/app-emulation/wine-2.17-r1/work/wine-2.17/fonts/courier.ttf -d 128 13,1255,8
Error: Cannot open face /var/tmp/portage/app-emulation/wine-2.17-r1/work/wine-2.17/fonts/courier.ttf
```

**Comment by bobwya** [comment]
I've pushed an update to all my Overlay **app-emulation/wine{-staging,-vanilla}** packages which should make your issue clear!

I won't revision bump my Wine packages - since this **>=media-libs/freetype-2.8.1** issue is posted widely already ( e.g. [Gentoo Bug 631376 - app-emulation/wine* - Error: Cannot open face /var/tmp/portage/app-emulation/wine-any-2.16/work/wine-2.16/fonts/courier.ttf ](https://bugs.gentoo.org/631376) )...

Just resync the **::bobwya** Overlay.

**Comment by stefantalpalaru** [comment]
There's a short patch available for Wine: https://bugs.winehq.org/attachment.cgi?id=59266&action=diff

**Comment by bobwya** [comment]
There are multiple issues in play here... As far as I'm aware there is not single patch fix for both the build and runtime issues. What about [freetype 2.8.1 breaks Wine build during font conversion with sfnt2fon](https://bugs.winehq.org/show_bug.cgi?id=43716) ? Even the _official_ **Arch Linux** wine package has not been fixed - at present.

I'm not particularly invested in fixing this issue - as I'm still running on an older **=media-libs/freetype-2.6.3** package... The newer packages don't add anything useful...

You are welcome to test out the patch yourself and report back though!

**Comment by stefantalpalaru** [comment]
I downgraded to freetype-2.8 because of this other bug: https://bugs.gentoo.org/631502

**Comment by bobwya** [comment]
I'll leave this issue open for now. If a concrete fix floats along - I'll quite happily backport it!

**Comment by bobwya** [comment]
I've backported the 3 patches that the Wine Development team have add to the Development branch (version 2.18). So all versions of my **app-emulation/wine**{,**-staging**,**-vanilla**} should now support **>=media-libs/freetype-2.8.1**.
