### ISSUE TITLE
app-eselect/eselect-wine should depend on sys-apps/mawk

### ISSUE THREAD

**Issue by stefantalpalaru** [bobwya/bobwya#18]
Without mawk installed:
```
root# eselect wine list
Available 'wine' versions:
which: no mawk in (/usr/x86_64-pc-linux-gnu/gcc-bin/6.4.0:/usr/i686-pc-linux-gnu/gcc-bin/4.5.3:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/opt/bin:/opt/nvidia-cg-toolkit/bin:/opt/vmware/bin:/opt/cuda/bin:/opt/bin:/usr/games/bin:~/scripts:/usr/local/games:~/bin)
awk: cmd. line:18: warning: escape sequence `\[' treated as plain `['
awk: cmd. line:18: warning: escape sequence `\(' treated as plain `('
awk: cmd. line:18: (FILENAME=- FNR=1) fatal: Unmatched ( or \(: /([[[:digit:]]*[mGK]|([B[[:digit:]]*)/
```

**Comment by bobwya** [comment]
The test for **mawk** vs. **awk** was wrong actually ... Well to be frank an eselect module is not really the right place to be using a big, embedded awk script. :-)

Anyway I've refactored out the worst hacks in the **eselect-wine** script. It also now correctly supports the global **eselect** parameters: **--brief** and **--colour=<no|yes|auto>**

Please sync the **::bobwya Overlay** and re-test with:
```=app-eselect/eselect-wine-1.5.2```

**Comment by stefantalpalaru** [comment]
Problem fixed by the new version.
