### ISSUE TITLE
Emerging wine-vanilla-3.1-r1 fails because of programs/msiexec/msiexec.man not existing

### ISSUE THREAD

**Issue by IvanDSM** [bobwya/bobwya#19]
I tried to emerge the app-emulation/wine-vanilla-3.1-r1 package twice and it fails during the sandboxed install process due to programs/msiexec/msiexec.man not being found. The build.log is attached.

[build.log](https://github.com/bobwya/bobwya/files/1719865/build.log)

**Comment by bobwya** [comment]
@IvanDSM 
Ah yeah... Sorry 'bout that! I didn't test building with -**l10n_en** - which would disable the base manpages ... I've reverted back to always building the base manpages. Can you retest with **=app-emulation/wine-vanilla-3.1-r2**. Thanks.

**Comment by IvanDSM** [comment]
This fixed it! Thanks, bobwya! That was really fast! :D

**Comment by IvanDSM** [comment]
Bob, I was gonna report an issue on your wine-desktop-common package but can't file an issue there, is it ok if I do it here instead?

**Comment by bobwya** [comment]
@IvanDSM 
You **can** raise issues **now**: [Issues * Github: bobwya / wine-desktop-common](https://github.com/bobwya/wine-desktop-common/issues) !
