### ISSUE TITLE
Manifest not found

### ISSUE THREAD

**Issue by arkhan** [bobwya/bobwya#2]
I have this message:
Calculating dependencies / * Manifest not found for '/var/lib/layman/bobwya/net-p2p/syncthing/syncthing-9999.ebuild'

**Comment by bobwya** [comment]
Sorry I meant to remove this package a while ago. I'm actually pulling (my local copy) from the mva overlay - which works well. I don't like to duplicate effort! I've nix'd it from my overlay now...
