### ISSUE TITLE
wine 3.6 gentooLTO

### ISSUE THREAD

**Issue by funghetto** [bobwya/bobwya#23]
Hi, I remember that you are using O3, LTO & graphite, does it fail to compile for you too?

**Comment by bobwya** [comment]
Well technically **sys-config/ltoize** already introduces this stock workaround:

```app-emulation/wine* "has custom-cflags ${IUSE//+} && use custom-cflags && FlagSubAllFlags -flto* ${GRAPHITE}" # In function ‘arc2polybezier’: gdiplus.c:223:5: internal compiler error: in extract_affine, at graphite-sese-to-poly.c:272```

to **/etc/portage/package.cflags/ltoworkarounds.conf** .

This will disable **graphite** and **LTO** support for all wine packages...
So I usually just compile **app-emulation/wine-*** with **-O3** .
