### ISSUE TITLE
winetricks attempts to pull in Gentoo's virtual/wine

### ISSUE THREAD

**Issue by kozross** [bobwya/bobwya#24]
Specifically as so:

```
[koz@Sebastian ~]$ sudo emerge --ask --verbose winetricks::bobwya

These are the packages that would be merged, in order:

Calculating dependencies... done!
[ebuild  N     ] app-arch/cabextract-1.6::gentoo  USE="-extras" 237 KiB
[ebuild  N     ] app-arch/p7zip-16.02-r3::gentoo  USE="pch -doc -kde -rar (-static) -wxwidgets" ABI_X86="(-x32)" 4,141 KiB
[ebuild  N     ] virtual/wine-0-r6::gentoo  USE="-d3d9 -staging" ABI_X86="32 64" 0 KiB
[ebuild  N     ] app-emulation/winetricks-20180513::bobwya  USE="-gtk -kde -rar {-test}" 638 KiB

Total: 4 packages (4 new), Size of downloads: 5,014 KiB

Would you like to merge these packages? [Yes/No]
```

Should I be concerned, given that I have ``virtual/wine::bobwya`` already installed?

**Comment by bobwya** [comment]
I'm using the following package mask locally:

```
/etc/portage/package.mask/gentoo

app-emulation/wine-mono::gentoo
app-emulation/wine-gecko::gentoo
app-emulation/wine::gentoo
app-emulation/wine-d3d9::gentoo
app-emulation/wine-staging::gentoo
app-emulation/wine-any::gentoo
app-emulation/wine-desktop-common::gentoo
app-emulation/wine-vanilla::gentoo
virtual/wine::gentoo
```

Which is what I recommend in the Wiki page...  See: [Github: bobwya / bobwya Wiki / Wine Packages](https://github.com/bobwya/bobwya/wiki/Wine-Packages).

**virtual/wine** is just a place-holder package for any version of Wine being installed on your system... So it's normal it would be installed... Just you want this Overlay's version of  the **virtual/wine** package - not the main Gentoo one (which is frankly a bit of a mess - but has a higher version / revision number!)

Btw let me know if you find any issues with the **winetricks** BASH completion script. Austin says he hopes to commit this patch (in **winetricks** Upstream) this week.

**winetricks** verbs are completed by default. Short options are completed once you've typed in a single dash characters ( **-** ) and Long options are completed once you've typed two dash characters ( **--** ). Reduces the visual overhead!

Thanks

**Comment by kozross** [comment]
@bobwya Thank you for pointing me in the right direction - that solved it. I'll make sure to RTFM more carefully next time.
