### ISSUE TITLE
move kde patchset to a use flag?

### ISSUE THREAD

**Issue by prototype99** [bobwya/bobwya#25]
obviously it is merely a suggestion, but over at https://github.com/perfect7gentleman/pg_overlay they put the opensuse patches inside a kde use flag, could this be a better solution?

**Comment by prototype99** [comment]
I just figure, if someone makes a dependency on Firefox, obviously this would break it? so it prevents that. but yeah let's see how it goes anyway

**Comment by prototype99** [comment]
oh! just realised you haven't updated the readme.md! just a minor thing obviously

**Comment by bobwya** [comment]
Ah yes, I've updated the README and Wiki page. Thanks.
