### ISSUE TITLE
nvidia-drivers-396.24.02 fails in install phase

### ISSUE THREAD

**Issue by HikloLime** [bobwya/bobwya#27]
Hi! When compiling nvidia-drivers-396.24.02 fails when trying to install modules. :) 

This is a wgetpaste of emerge --info:
https://paste.pound-python.org/show/AcJoXIoCfUl1tcm0vY4q/

And this is a gist of the full build log (with stripped color codes):
https://gist.github.com/HikloLime/e0b558499a17be4dc5286ef2868af625

And this is the emrge --pqv =x11-drivers/nvidia-drivers-396.24.02:
`[ebuild     U ] x11-drivers/nvidia-drivers-396.24.02 [396.24-r1] USE="X driver kms multilib tools -acpi -compat -gtk3 -pax_kernel -static-libs -uvm -wayland" ABI_X86="32 (64) (-x32)"`

EDIT: Cleaned up this terrible mess!

**Comment by HikloLime** [comment]
Sorry for crappy formating, I dont know how to submit code and I couldn't upload full build code for some reason.

**Comment by bobwya** [comment]
I need the full build log for the **x11-drivers/nvidia-drivers** package.

Please post the full build log in a **Github Gist** .

Please **do not** post this build log inline in an Issue comment.

**Comment by HikloLime** [comment]
Sorry for the terrible formatting! I will keep that in mind for the future!
Here is the build log: https://gist.github.com/HikloLime/e0b558499a17be4dc5286ef2868af625
I stripped away all the color codes, (I think) but if there is some information missing it's probably my fault!
Thanks for responding :)

**Comment by bobwya** [comment]
@HikloLime 

```
 * ERROR: x11-drivers/nvidia-drivers-396.24.02::bobwya failed (install phase):
 *   Invalid parameter (2) directory: "/usr/lib64/xorg/nvidia/extensions"
 * 
 * Call stack:
 *     ebuild.sh, line  124:  Called src_install
 *   environment, line 4917:  Called donvidia '/var/tmp/portage/x11-drivers/nvidia-drivers-396.24.02/work/libglx.so.396.24.02' '/usr/lib64/xorg/nvidia/extensions'
 *   environment, line 1143:  Called die
 * The specific snippet of code:
 *       [[ -z "${2}" || ! -d "${2}" ]] && die "Invalid parameter (2) directory: \"${2}\"";
```

This package can _only_ be used as part of the set of custom GL switching applications in my Overlay. See the "**Custom GL lib switcher implementation package set**" entry in the repository **README** file. I'd recommend against using it, unless you know what you are doing. The current implementation has a number of flaws anyway (e.g. symbolic links, for switching GL targets, are currently not tracked).

_Which is why this package set is hard-masked in the Overlay profile._
