### ISSUE TITLE
Error when syncing: External commands disallowed while sourcing ebuild

### ISSUE THREAD

**Issue by fluffynuts** [bobwya/bobwya#30]
Apparently portage has had an update which disallows running commands whilst sourcing an ebuild. I see a lot of these:

```
build failed with status 1
     Reading category  13|165 (  7): app-emulation...
cannot properly execute /var/lib/layman/bobwya/app-emulation/wine-vanilla/wine-vanilla-3.7-r1.ebuild
     Reading category  13|165 (  7): app-emulation... * ERROR: app-emulation/wine-vanilla-3.8-r2::bobwya failed (depend phase):
 *   External commands disallowed while sourcing ebuild: ver_rs 1-  
 * 
 * Call stack:
 *                    ebuild.sh, line 635:  Called source '/var/lib/layman/bobwya/app-emulation/wine-vanilla/wine-vanilla-3.8-r2.ebuild'
 *   wine-vanilla-3.8-r2.ebuild, line  15:  Called command_not_found_handle 'ver_rs' '1-' ' '
 *                    ebuild.sh, line  88:  Called die
 * The specific snippet of code:
 *              die "External commands disallowed while sourcing ebuild: ${*}"
 * 
 * If you need support, post the output of `emerge --info '=app-emulation/wine-vanilla-3.8-r2::bobwya'`,
 * the complete build log and the output of `emerge -pqv '=app-emulation/wine-vanilla-3.8-r2::bobwya'`.
 * Working directory: '/usr/lib64/python2.7/site-packages'
 * S: '/wine-vanilla-3.8'

```

**Comment by bobwya** [comment]
@fluffynuts 

What tool are you using to sync your Gentoo Overlays...
Because whatever it is - it is out-of-date.
**EAPI 7** is supported by the current Portage release.

**Comment by bobwya** [comment]
Closing due to a lack of any end-user response...

**Comment by fluffynuts** [comment]
Apologies -- I have so many GH notifications that I didn't see this. 

I'm just using emerge (--version gives `Portage 2.3.40 (python 2.7.14-final-0, default/linux/amd64/17.0/desktop/plasma, gcc-7.3.0, glibc-2.26-r7, 4.14.52-gentoo x86_64)`). I've just re-run a sync and I get the same errors. According to `equery y portage`, I'm using the latest stable release. Is there something else I should check?

**Comment by fluffynuts** [comment]
ok, so please bear with me:

I've only been using gentoo for about 1.5 years, having come from around 17 years in a debian-based world (debian, ubuntu, mint; mixed up). So 2.3.44 is _current unstable_; 2.3.40 is _current stable_ -- I'm using the "safer" option, so my questions are:
1) do the warnings matter? I really only use `filebot` from your overlay (haven't looked into other items you provide, but that's why I came here to start with)
2) if I were to, eg, `ACCEPT_KEYWORDS="~amd64" emerge -1 portage`, what are the ramifications for my system? Is this a bad thing? can I have _just_ portage at ~amd64? I really don't want my entire system at ~amd64, so I'm not about to set that flag globally. I've done ~amd64 only where really necessary, after having been burned by other distros and their 'unstable' branches not just being "changing often", but also being "breaks often" (and the gentoo user group emails I've seen suggest this is probably true for gentoo too -- which is ok if you're into fixing that kind of stuff, but the older I get, the fewer fux I have left to give about that, so I'm preferring stable)
3) is there a way for an ebuild to detect this versioning and behave differently? If so, is that a route you can take? I don't want to make a mess of work to do so -- and (not having dived into the ebuilds, personally), it looks like you're doing a "good thing" with shared code in a sourced file, so, if I'm correct, I'm all for that, but if there's a way to behave "both ways", that would be cool too.

Apologies for rambling and all that. Just trying to figure out what I should do from here. Thanks for your time and your overlay.

**Comment by bobwya** [comment]
@fluffynuts 

You've essentially got 3 main options:

- Copy the **media-video/filebot** package to a local Portage Overlay on your system.

- Unmask the unstable version of Portage:
```
  mkdir -p "/etc/portage/package.accept_keywords/"
  echo "sys-apps/portage                ~amd64" >>"/etc/portage/package.accept_keywords/sys-apps.keywords"
```

- Ignore the warnings you get, on every Portage sync. They are just outdated Q/A warnings...

The warnings do not matter at all and will go away, after you update to the **2.3.44** version (now or later on). What is essentially happening is that your older version of Portage is following outdated Q/A standards and (incorrectly) warning about the items from the next generation of Gentoo tooling (EAPI version 7).

There's no easy fix at my end... I'd just end adding hacks, for little purpose. As far as I'm concerned I've discharged my obligations by: supporting  a key-worded version of Portage and by filing a bug Upstream against the **eix** tool (which is fixed in the Master branch).

I'm working to remove Q/A warnings, generated by the **current** Gentoo toolkit / **repoman** and move over to supporting **EAPI 7**. 

Bob

**Comment by fluffynuts** [comment]
Thanks for getting back to me. If the warnings are unimportant, I'll just ignore them until portage 2.3.44 becomes stable. I was concerned that the warnings would mean that your overlay would become unusable for me. I don't really want to go ~amd64 with portage -- I don't feel that I know enough about it that if there is an issue, I'd be able to fix it. Portage is a bit of a keystone in the whole process -- if I can't emerge, I'll be quite lost.

I agree that you adding hacks would be pointless, given that the warnings are just warnings and don't underly a real problem. I tend to treat warnings with (probably) higher priority than a lot of my peers, because whilst many may be essentially unimportant, it's the 1 or 2 in 100 which are clues about a way bigger problem, which is why I raised this. You obviously know more about portage than I do, so I trust that the warnings are, as you say, unimportant. I'll just wait them out (:

Thanks for all your time and effort.
