### ISSUE TITLE
unfinished merge?

### ISSUE THREAD

**Issue by prototype99** [bobwya/bobwya#31]
it says this:
* Running Git... # ( cd /var/lib/layman/bobwya  && /usr/bin/git pull )
error: You have not concluded your merge (MERGE_HEAD exists).
hint: Please, commit your changes before merging.
fatal: Exiting because of unfinished merge.

**Comment by bobwya** [comment]
@prototype99 

Sorry 'bout that... But I can't see any issues at my end.

What I'd suggest is:
```
layman -d bobwya
layman -a bobwya
```
to clean up your local copy of the Overlay (which sounds like has gotten a bit corrupted). That's what I do if I make any hacky changes to an Overlay on my system - that I want to wipe away.

I'd recommend to use the official Gentoo tools for syncing Overlays..
```
emerge --sync bobwya
layman -s bobwya
```
I wouldn't recommend doing this manually with **git**...

**Comment by prototype99** [comment]
oh okay i've never experienced that with overlays. this was with layman, but i'll keep that in mind next time that happens
