### ISSUE TITLE
app-portage/smart-live-rebuild-1.3.6 tries to re-emerge firefox-61.0.1-r1 after a [KeyError] "Environment does not declare: ['HG_REV_ID']"

### ISSUE THREAD

**Issue by stefantalpalaru** [bobwya/bobwya#32]
The weird part is that it's not even a live ebuild of firefox. Must be an unwanted consequence of this firefox-related error:

!!! Error enumerating =www-client/firefox-61.0.1-r1: [KeyError] "Environment does not declare: ['HG_REV_ID']"

**Comment by bobwya** [comment]
Yeah I use:

```
/etc/portage/smart-live-rebuild.conf

[smart-live-rebuild]
jobs = 8
type=git,subversion
filter=!www-client/firefox,!mail-client/thunderbird
# quickpkg = on
```

locally.

**www-client/firefox** uses **mercurial** (as does **mail-client/thunderbird**) to pull the correct OpenSUSE patchset version. Hence the **['HG...']** error message...

**Comment by stefantalpalaru** [comment]
How about defining EHG_REVISION unconditionally, not just when the 'kde' USE flag is enabled?

**Comment by bobwya** [comment]
@stefantalpalaru 

I'm not really convinced that's a good idea. Basically **smart-live-rebuild** should ignore this package - _because it does not have a live version_. It's a bug in the **smart-live-rebuild** script as far as I am concerned. It should ignore non-**9999** / **99999999** package versions. I see no reason for me to workaround this downstream...

**Comment by stefantalpalaru** [comment]
> It should ignore non-9999 / 99999999 package versions.

But it doesn't limit itself to the version number to determine whether an ebuild is "live". There must be a reason for that. Maybe some versioned ebuilds have live components.
