### ISSUE TITLE
wine-staging-4.3_p1 needs wine-mono:4.8.0

### ISSUE THREAD

**Issue by Faunenschnitt** [bobwya/bobwya#37]
Hello bobwya,
can you also update wine-mono in your overlay? I cannot merge wine-staging-4.3_p1 otherwise.

emerge -pv =app-emulation/wine-staging-4.3_p1
These are the packages that would be merged, in order:
Calculating dependencies... done!
emerge: there are no ebuilds to satisfy "app-emulation/wine-mono:4.8.0".
(dependency required by "app-emulation/wine-staging-4.3_p1::bobwya[mono]" [ebuild])
(dependency required by "=app-emulation/wine-staging-4.3_p1" [argument])

**Comment by bobwya** [comment]
Ah went to bed v. late, so missed the Travis CI warnings about that... I've pushed (the local) **wine-mono** update now.
