### ISSUE TITLE
wine-esync patchset regression affecting wine-vanilla:4.5 + wine-staging:4.5

### ISSUE THREAD

**Issue by bobwya** [bobwya/bobwya#39]
Currently there is a delay releasing:

- **app-emulation/wine-staging:4.5**
- **app-emulation/wine-vanilla:4.5**

When build with USE +**esync** and **esync** is enabled, launching the Windows Steam client is broken. This is a significant regression vs.:

- **app-emulation/wine-staging:4.4**
- **app-emulation/wine-vanilla:4.4**

Some regression testing is required.

[wine-vanilla-4.5_steam_esync_on_log.txt](https://github.com/bobwya/bobwya/files/3041114/wine-vanilla-4.5_steam_esync_on_log.txt)

**Comment by bobwya** [comment]
The wine-esync regression is caused by: [b2a546c92dabee8ab1c3d5b9fecc84d99caf0e76](https://source.winehq.org/git/wine.git/commit/b2a546c92dabee8ab1c3d5b9fecc84d99caf0e76)

**Comment by funghetto** [comment]
It seems that esync has been merged into wine-staging-git.
https://github.com/wine-staging/wine-staging/commit/553986fdfb111914f793ff1487d53af022e4be19

**Comment by bobwya** [comment]
@funghetto 

I've already pushed **wine-esync** fixes for **app-emulation/wine-vanilla:4.5** , **app-emulation/wine-vanilla:9999** and **app-emulation/wine-staging:4.5** .
I've also already updated **app-emulation/wine-staging:9999** with support for the integrated **eventfd_synchronization** patchset ...
