### ISSUE TITLE
app-benchmarks/phoronix-test-suite-6.0.1 should not access files outside the image directory

### ISSUE THREAD

**Issue by stefantalpalaru** [bobwya/bobwya#4]
I was hit by this when upgrading from a previous version where I had some script files installed that were not in the image directory so chmod was failing. The fix is changing this line:

```sh
find /usr/share/${PN}/pts-core/ -type f -name "*.sh" -print0 | xargs -0 fperms a+x
```

into

```sh
find ${D}/usr/share/${PN}/pts-core/ -type f -name "*.sh" -print0 | sed "s#${D}##g" | xargs -0 fperms a+x
```

I haven't looked at the other package versions, see if it applies.

**Comment by bobwya** [comment]
Hi Ștefan,
Sorry I seemed to have buggered up the ebuild with my latest "tweaks". I've cleaned up the mess (regular commands not referencing absolute paths and Gentoo ebuild functions not referencing sandbox relative paths).
I'm (pretty) sure all the references are all correct now... All versions of the package build cleanly. You're welcome to re-open the issue if there's still a problem at your end...
Bob
