### ISSUE TITLE
hello wine staging failed with this :

### ISSUE THREAD

**Issue by javashin** [bobwya/bobwya#41]
>>> Emerging (6 of 39) app-emulation/wine-staging-4.7_p1::bobwya
 * gentoo-wine-ebuild-common-20190428.tar.gz SHA256 SHA512 WHIRLPOOL size ;-) ...                                                              [ ok ]
 * wine-4.7.tar.xz SHA256 SHA512 WHIRLPOOL size ;-) ...                                                                                        [ ok ]
 * wine-staging-4.7.tar.gz SHA256 SHA512 WHIRLPOOL size ;-) ...                                                                                [ ok ]
wine-staging: Fri Apr  5 08:43:35 2019: 1 hour, 2 minutes, 50 seconds
wine-staging: Fri Apr  5 12:43:52 2019: 2 hours, 5 minutes, 19 seconds
wine-staging: Fri Apr  5 20:25:13 2019: 52 minutes, 12 seconds
wine-staging: Sun Apr  7 07:42:24 2019: 1 hour, 4 minutes, 39 seconds
wine-staging: Sun Apr 14 11:06:05 2019: 1 hour, 9 minutes, 45 seconds
wine-staging: 5 times
wine-staging: 1 hour, 14 minutes, 57 seconds for 5 merges
 * /etc/portage/package.cflags/ltoworkarounds.conf -> app-emulation/wine*: *FLAGS-=-flto*
 * FEATURES='binpkg-logs usersandbox distlocks ccache userpriv preserve-libs unknown-features-warn assume-digests news xattr userfetch network-sandbox sfperms config-protect-if-modified protect-owned strict sandbox ipc-sandbox binpkg-docompress unmerge-logs pid-sandbox parallel-fetch usersync fixlafiles multilib-strict unmerge-orphans binpkg-dostrip merge-sync ebuild-locks'
 * CFLAGS='-O3 -march=native -pipe -Wl,-O2 -Wl,--as-needed -Wl,--hash-style=gnu'
 * CXXFLAGS='-O3 -march=native -pipe -Wl,-O2 -Wl,--as-needed -Wl,--hash-style=gnu'
 * CPPFLAGS='-O3 -march=native -pipe'
 * FFLAGS='-O3 -march=native -pipe -Wl,-O2 -Wl,--as-needed -Wl,--hash-style=gnu'
 * FCFLAGS='-O3 -march=native -pipe -Wl,-O2 -Wl,--as-needed -Wl,--hash-style=gnu'
 * F77FLAGS='-O3 -march=native -pipe -Wl,-O2 -Wl,--as-needed -Wl,--hash-style=gnu'
 * LDFLAGS='-Wl,-O2 -Wl,--as-needed -Wl,--hash-style=gnu'
 * MAKEOPTS='-j2'
 * gcc (Gentoo 8.3.0-r1 p1.1) 8.3.0
 * Linux igloo-l440 5.0.10-gentoo #1 SMP PREEMPT Tue Apr 30 23:00:15 AST 2019 x86_64 Intel(R) Core(TM) i5-4200M CPU @ 2.50GHz GenuineIntel GNU/Linux
>>> Unpacking source...
>>> Unpacking gentoo-wine-ebuild-common-20190428.tar.gz to /var/tmp/portage/app-emulation/wine-staging-4.7_p1/work
>>> Unpacking wine-4.7.tar.xz to /var/tmp/portage/app-emulation/wine-staging-4.7_p1/work
>>> Unpacking wine-staging-4.7.tar.gz to /var/tmp/portage/app-emulation/wine-staging-4.7_p1/work
 * Looking in /var/tmp/portage/app-emulation/wine-staging-4.7_p1/work/wine-4.7/po for new locales ...                                          [ ok ]
>>> Source unpacked in /var/tmp/portage/app-emulation/wine-staging-4.7_p1/work
>>> Preparing source in /var/tmp/portage/app-emulation/wine-staging-4.7_p1/work/wine-4.7 ...
 * Applying the Wine Staging patchset. Any bug reports to Wine Bugzilla
 * should explicitly state that Wine Staging was used.
 * Ignoring Wine Staging patchset: "configure-OSMesa"
 * Ignoring Wine Staging patchset: "winhlp32-Flex_Workaround"
 * Ignoring Wine Staging patchset: "quartz-NULL_TargetFormat"
 * Excluding Wine Staging patchset: "eventfd_synchronization"
 * Excluding Wine Staging patchset: "xaudio2_7-CreateFX-FXEcho"
 * Excluding Wine Staging patchset: "xaudio2_7-WMA_support"
 * Excluding Wine Staging patchset: "xaudio2_CommitChanges"
 * Excluding Wine Staging patchset: "winepulse-PulseAudio_Support"
 * Excluding Wine Staging patchset: "xaudio2-revert"
 * Excluding Wine Staging patchset: "Pipelight"
 * Running Wine-Staging patch installer ...
 * ERROR: app-emulation/wine-staging-4.7_p1::bobwya failed (prepare phase):
 *   Patchset eventfd_synchronization disabled, but server-Desktop_Refcount depends on that.
 * 
 * Call stack:
 *         ebuild.sh, line  124:  Called src_prepare
 *       environment, line 4435:  Called wine_eapply_staging_patchset
 *       environment, line 5675:  Called source '/var/tmp/portage/app-emulation/wine-staging-4.7_p1/work/wine-staging-4.7/patches/patchinstall.sh'
 *   patchinstall.sh, line 1758:  Called die
 * The specific snippet of code:
 *   		die "Patchset eventfd_synchronization disabled, but server-Desktop_Refcount depends on that."
 * 
 * If you need support, post the output of `emerge --info '=app-emulation/wine-staging-4.7_p1::bobwya'`,
 * the complete build log and the output of `emerge -pqv '=app-emulation/wine-staging-4.7_p1::bobwya'`.
 * The complete build log is located at '/var/tmp/portage/app-emulation/wine-staging-4.7_p1/temp/build.log'.
 * The ebuild environment file is located at '/var/tmp/portage/app-emulation/wine-staging-4.7_p1/temp/environment'.
 * Working directory: '/var/tmp/portage/app-emulation/wine-staging-4.7_p1/work/wine-4.7'
 * S: '/var/tmp/portage/app-emulation/wine-staging-4.7_p1/work/wine-4.7'

>>> Failed to emerge app-emulation/wine-staging-4.7_p1, Log file:

>>>  '/var/tmp/portage/app-emulation/wine-staging-4.7_p1/temp/build.log'

 * Messages for package kde-frameworks/kfilemetadata-5.57.0-r1:

 * To get additional features, optional runtime dependencies may be installed:
 * app-text/catdoc - indexing of Microsoft Word or Powerpoint files
 * dev-libs/libxls - indexing of Microsoft Excel files

 * Messages for package app-emulation/wine-staging-4.7_p1:

 * Applying the Wine Staging patchset. Any bug reports to Wine Bugzilla
 * should explicitly state that Wine Staging was used.
 * ERROR: app-emulation/wine-staging-4.7_p1::bobwya failed (prepare phase):
 *   Patchset eventfd_synchronization disabled, but server-Desktop_Refcount depends on that.
 * 
 * Call stack:
 *         ebuild.sh, line  124:  Called src_prepare
 *       environment, line 4435:  Called wine_eapply_staging_patchset
 *       environment, line 5675:  Called source '/var/tmp/portage/app-emulation/wine-staging-4.7_p1/work/wine-staging-4.7/patches/patchinstall.sh'
 *   patchinstall.sh, line 1758:  Called die
 * The specific snippet of code:
 *   		die "Patchset eventfd_synchronization disabled, but server-Desktop_Refcount depends on that."
 * 
 * If you need support, post the output of `emerge --info '=app-emulation/wine-staging-4.7_p1::bobwya'`,
 * the complete build log and the output of `emerge -pqv '=app-emulation/wine-staging-4.7_p1::bobwya'`.
 * The complete build log is located at '/var/tmp/portage/app-emulation/wine-staging-4.7_p1/temp/build.log'.
 * The ebuild environment file is located at '/var/tmp/portage/app-emulation/wine-staging-4.7_p1/temp/environment'.
 * Working directory: '/var/tmp/portage/app-emulation/wine-staging-4.7_p1/work/wine-4.7'
 * S: '/var/tmp/portage/app-emulation/wine-staging-4.7_p1/work/wine-4.7'

 * Regenerating GNU info directory index...
 * Processed 150 info files.
 * After world updates, it is important to remove obsolete packages with
 * emerge --depclean. Refer to `man emerge` for more information.

**Comment by javashin** [comment]
Patchset eventfd_synchronization disabled, but server-Desktop_Refcount depends on that.

**Comment by bobwya** [comment]
See the smaller box at the bottom of the edit box that says: "Attach file by dragging & dropping, selecting or pasting them."

So please don't spam an Issue with badly formatted terminal output. Just, in future, **_attach a log file_**!

Surely Gentoo user's should know better than this...

**Comment by javashin** [comment]
Ok Man Thanks I saw it was solved after resync a few days a go no pasting anything anymore here thanks

**Comment by javashin** [comment]
Cool
