### ISSUE TITLE
hi app-emulation/wine-vanilla-4.10_p1-r1 broken

### ISSUE THREAD

**Issue by javashin** [bobwya/bobwya#43]
https://gist.github.com/javashin/3849624772c348fc3d8d235e6dbf6791

**Comment by javashin** [comment]
Broken using paludis too 
https://gist.github.com/javashin/0f199db65f25952e4aefc7bc0f3a36da

**Comment by bobwya** [comment]
@javashin 

It's because your awk implementation is set to **gawk** - which not standards compliant and also incredibly inefficient (I'd recommend installing/ using **mawk** - which is truly Posix complaint and much better optimised).

I'll push a **gawk** workaround as soon as I can.

**Comment by javashin** [comment]
ok let me try mawk

**Comment by javashin** [comment]
Ok is working
