### ISSUE TITLE
games-util/lutris-9999 missing dep

### ISSUE THREAD

**Issue by mitch1887** [bobwya/bobwya#46]
To run lutris I needed to emerge dev-python/dbus-python, otherwise I got the error: ModuleNotFoundError: No module named 'dbus'

**Comment by bobwya** [comment]
That package  is already a runtime dependency for my:
`=games-util/lutris-9999`
package.

Checking at: [games-util/lutris-9999.ebuild](https://github.com/bobwya/bobwya/blob/master/games-util/lutris/lutris-9999.ebuild)
