### ISSUE TITLE
wine staging fails postinstall

### ISSUE THREAD

**Issue by Alex-Aralis** [bobwya/bobwya#49]
app-emulation/wine-staging-5.14 fails with 

```
ERROR: postinst
FAILED postinst: 1
ERROR: app-emulation/wine-staging-5.14::gentoo failed (postinst phase):
  (no error message)

Call stack:
    ebuild.sh, line 125:  Called pkg_postinst
  environment, line 3754:  Called die
The specific snippet of code:
      eselect wine update --all --if-unset || die;
```

Seems that it expects `eselect wine` to have an update command but that is not listed anywhere in the documentation. I have the most up to date eselect-wine package installed. app-eselect/eselect-wine-1.5.5::bobwya

**Comment by bobwya** [comment]
You cannot mix-n-match **::gentoo** and **::bobwya** Wine, or Wine-support, packages.

See: [Wiki: Wine Packages](https://github.com/bobwya/bobwya/wiki/Wine-Packages)
