### ISSUE TITLE
emerge --sync promting for github login when syncing bobwya repo

### ISSUE THREAD

**Issue by RaphaelNeubert** [bobwya/bobwya#51]
Syncing this repository with emerge --sync or emaint fails.
`>>> Syncing repository 'bobwya' into '/var/db/repos/bobwya'...
/usr/bin/git fetch origin
Username for 'https://github.com':
Password for 'https://              @github.com':
remote: Invalid username or password.
fatal: Authentication failed for 'https://github.com/gentoo-mirror/bobwya.git/'
!!! git fetch error in /var/db/repos/bobwya
`
this has been happening for a few weeks now.

**Comment by bobwya** [comment]
What's the output from:
`grep bobwya -R /etc/portage/repos.conf*`

Looks like the Layman repository address was setup wrongly (when I originally submitted it)...

**Comment by RaphaelNeubert** [comment]
The output is:
```
/etc/portage/repos.conf/eselect-repo.conf:[bobwya]
/etc/portage/repos.conf/eselect-repo.conf:location = /var/db/repos/bobwya
/etc/portage/repos.conf/eselect-repo.conf:sync-uri = https://github.com/gentoo-mirror/bobwya.git
```
I added your repo with eselect repository, not with layman.

**Comment by bobwya** [comment]
@RaphaelNeubert 

I'll need to get the Github repository name - **bobwya** - to match up with the Gentoo Overlay entry- **miscellaneous_ebuilds** ...
Hopefully this will be easy to sort out.
I didn't really mean to say **Layman** (as in it's just the list that Layman accesses).

In the meantime, you can change fix the entry with:

`sed -i -e 's|gentoo-mirror|bobwya|' /etc/portage/repos.conf/eselect-repo.conf`

That should work!

Bob

**Comment by RaphaelNeubert** [comment]
Just changing the entry in eselect-repo.conf wasn't enough, it was still trying to source the old link.
I removed the repository with `eselect repository remove -f bobwya` and added it again with `eselect repository add bobwya git https://github.com/bobwya/bobwya.git`. Now it's working.
Thank you very much for you help and for making your ebuilds public.
