### ISSUE TITLE
Build failure with new ebuild

### ISSUE THREAD

**Issue by je-fro** [bobwya/bobwya#53]
I'm getting this:

[197/513] /usr/bin/x86_64-pc-linux-gnu-g++ -DD3_ARCH=\"x86_64\" -DD3_OSTYPE=\"linux\" -DD3_SIZEOFPTR=8 -D__DOOM_DLL__ -I/usr/include/AL -I/usr/include/SDL -I/var/tmp/portage/games-fps/dhewm3-1.5.2_rc1/work/dhewm3-1.5.2_rc1_build -I/var/tmp/portage/games-fps/dhewm3-1.5.2_rc1/work/dhewm3-1.5.2_RC1/neo  -march=native -O2 -pipe -pipe -Wall -fno-strict-aliasing -ffp-contract=off -fvisibility=hidden -Wno-sign-compare -Wno-switch -Wno-format-security -Woverloaded-virtual -Wno-class-memaccess -MD -MT CMakeFiles/dhewm3.dir/sys/threads.cpp.o -MF CMakeFiles/dhewm3.dir/sys/threads.cpp.o.d -o CMakeFiles/dhewm3.dir/sys/threads.cpp.o -c /var/tmp/portage/games-fps/dhewm3-1.5.2_rc1/work/dhewm3-1.5.2_RC1/neo/sys/threads.cpp
FAILED: CMakeFiles/dhewm3.dir/sys/threads.cpp.o
/usr/bin/x86_64-pc-linux-gnu-g++ -DD3_ARCH=\"x86_64\" -DD3_OSTYPE=\"linux\" -DD3_SIZEOFPTR=8 -D__DOOM_DLL__ -I/usr/include/AL -I/usr/include/SDL -I/var/tmp/portage/games-fps/dhewm3-1.5.2_rc1/work/dhewm3-1.5.2_rc1_build -I/var/tmp/portage/games-fps/dhewm3-1.5.2_rc1/work/dhewm3-1.5.2_RC1/neo  -march=native -O2 -pipe -pipe -Wall -fno-strict-aliasing -ffp-contract=off -fvisibility=hidden -Wno-sign-compare -Wno-switch -Wno-format-security -Woverloaded-virtual -Wno-class-memaccess -MD -MT CMakeFiles/dhewm3.dir/sys/threads.cpp.o -MF CMakeFiles/dhewm3.dir/sys/threads.cpp.o.d -o CMakeFiles/dhewm3.dir/sys/threads.cpp.o -c /var/tmp/portage/games-fps/dhewm3-1.5.2_rc1/work/dhewm3-1.5.2_RC1/neo/sys/threads.cpp
/var/tmp/portage/games-fps/dhewm3-1.5.2_rc1/work/dhewm3-1.5.2_RC1/neo/sys/threads.cpp:48:8: error: ‘SDL_threadID’ does not name a type; did you mean ‘SDL_Thread’?
   48 | static SDL_threadID mainThreadID = -1;
      |        ^~~~~~~~~~~~
      |        SDL_Thread
/var/tmp/portage/games-fps/dhewm3-1.5.2_rc1/work/dhewm3-1.5.2_RC1/neo/sys/threads.cpp: In function ‘void Sys_InitThreads()’:
/var/tmp/portage/games-fps/dhewm3-1.5.2_rc1/work/dhewm3-1.5.2_RC1/neo/sys/threads.cpp:74:9: error: ‘mainThreadID’ was not declared in this scope; did you mean ‘mainThreadIDset’?
   74 |         mainThreadID = SDL_ThreadID();
      |         ^~~~~~~~~~~~
      |         mainThreadIDset
/var/tmp/portage/games-fps/dhewm3-1.5.2_rc1/work/dhewm3-1.5.2_RC1/neo/sys/threads.cpp: In function ‘bool Sys_IsMainThread()’:
/var/tmp/portage/games-fps/dhewm3-1.5.2_rc1/work/dhewm3-1.5.2_RC1/neo/sys/threads.cpp:333:42: error: ‘mainThreadID’ was not declared in this scope; did you mean ‘mainThreadIDset’?
  333 |                 return SDL_ThreadID() == mainThreadID;
      |                                          ^~~~~~~~~~~~
      |                                          mainThreadIDset

**Comment by je-fro** [comment]
Portage 3.0.30 (python 3.10.4-final-0, default/linux/amd64/17.1/desktop, gcc-11.3.0, glibc-2.35-r5, 5.17.9-gentoo x86_64)
=================================================================
                         System Settings
=================================================================
System uname: Linux-5.17.9-gentoo-x86_64-Intel-R-_Xeon-R-_CPU_E3-1270_v5_@_3.60GHz-with-glibc2.35
KiB Mem:    65675404 total,    443212 free
KiB Swap:     524284 total,    483324 free
Timestamp of repository gentoo: Fri, 27 May 2022 15:30:01 +0000
Head commit of repository gentoo: b01009f109239292d1354cc655cbbb1e2ac8b7fa
sh bash 5.1_p16
ld GNU ld (Gentoo 2.38 p4) 2.38
app-misc/pax-utils:        1.3.4::gentoo
app-shells/bash:           5.1_p16::gentoo
dev-java/java-config:      2.3.1::gentoo
dev-lang/perl:             5.34.1-r3::gentoo
dev-lang/python:           2.7.18_p15::gentoo, 3.9.13::gentoo, 3.10.4_p1::gentoo, 3.11.0_beta1-r2::gentoo
dev-lang/rust:             1.61.0-r1::gentoo
dev-util/cmake:            3.23.2::gentoo
dev-util/meson:            0.62.1::gentoo
sys-apps/baselayout:       2.8::gentoo
sys-apps/openrc:           0.44.10::gentoo
sys-apps/sandbox:          2.29::gentoo
sys-devel/autoconf:        2.13-r1::gentoo, 2.71-r1::gentoo
sys-devel/automake:        1.16.5::gentoo
sys-devel/binutils:        2.38-r2::gentoo
sys-devel/binutils-config: 5.4.1::gentoo
sys-devel/clang:           13.0.1::gentoo, 14.0.3::gentoo
sys-devel/gcc:             11.3.0::gentoo
sys-devel/gcc-config:      2.5-r1::gentoo
sys-devel/libtool:         2.4.7::gentoo
sys-devel/lld:             14.0.3::gentoo
sys-devel/llvm:            13.0.1::gentoo, 14.0.3::gentoo
sys-devel/make:            4.3::gentoo
sys-kernel/linux-headers:  5.18::gentoo (virtual/os-headers)
sys-libs/glibc:            2.35-r5::gentoo
Repositories:

gentoo
    location: /usr/portage
    sync-type: rsync
    sync-uri: rsync://rsync.gentoo.org/gentoo-portage
    priority: -1000
    sync-rsync-verify-metamanifest: yes
    sync-rsync-verify-max-age: 24
    sync-rsync-extra-opts:
    sync-rsync-verify-jobs: 1

localrepo
    location: /usr/local/portage
    masters: gentoo

bitcoin
    location: /var/lib/layman/bitcoin
    masters: gentoo
    priority: 50

bobwya
    location: /var/lib/layman/bobwya
    masters: gentoo
    priority: 50

brother-overlay
    location: /var/lib/layman/brother-overlay
    masters: gentoo
    priority: 50

ceamac
    location: /var/lib/layman/ceamac
    masters: gentoo
    priority: 50

steam-overlay
    location: /var/lib/layman/steam-overlay
    masters: gentoo
    priority: 50

ACCEPT_KEYWORDS="amd64 ~amd64"
ACCEPT_LICENSE="* -@EULA PUEL QUAKE4 DOOM3 dlj-1.1 ETQW sun-bcla-java-vm googleearth AdobeFlash-10.1 AdobeFlash-10 google-talkplugin IBM-J1.6 Oracle-BCLA-JavaSE MakeMKV-EULA AdobeFlash-10.3 AdobeFlash-11.x Google-TOS google-chrome FAH-EULA-2009 FAH-EULA-2014 FraunhoferFDK Mojang ms-teams-pre NVIDIA-CUDA OPERA-2014 Microsoft-visualstudio-EULA supermicro ut2003"
CBUILD="x86_64-pc-linux-gnu"
CFLAGS="-march=native -O2 -pipe"
CHOST="x86_64-pc-linux-gnu"
CONFIG_PROTECT="/etc /opt/brother/scanner/brscan4/brsanenetdevice4.cfg /usr/lib64/libreoffice/program/sofficerc /usr/share/config /usr/share/gnupg/qualified.txt"
CONFIG_PROTECT_MASK="/etc/ca-certificates.conf /etc/dconf /etc/env.d /etc/fonts/fonts.conf /etc/gconf /etc/gentoo-release /etc/revdep-rebuild /etc/sandbox.d /etc/terminfo"
CXXFLAGS="-march=native -O2 -pipe"
DISTDIR="/usr/portage/distfiles"
--- replaced obj /usr/lib/python3.9/site-packages/trimesh/exchange/__pycache__/ply.cpython-39.pyc
ENV_UNSET="CARGO_HOME DBUS_SESSION_BUS_ADDRESS DISPLAY GOBIN GOPATH PERL5LIB PERL5OPT PERLPREFIX PERL_CORE PERL_MB_OPT PERL_MM_OPT XAUTHORITY XDG_CACHE_HOME XDG_CONFIG_HOME XDG_DATA_HOME XDG_RUNTIME_DIR"
FCFLAGS="-O2 -pipe"
FEATURES="assume-digests binpkg-docompress binpkg-dostrip binpkg-logs binpkg-multi-instance buildpkg-live config-protect-if-modified distlocks ebuild-locks fixlafiles ipc-sandbox merge-sync multilib-strict network-sandbox news parallel-fetch pid-sandbox preserve-libs protect-owned qa-unresolved-soname-deps sandbox sfperms strict unknown-features-warn unmerge-logs unmerge-orphans userfetch userpriv usersandbox usersync xattr"
FFLAGS="-O2 -pipe"
GENTOO_MIRRORS="https://gentoo.osuosl.org/ https://mirrors.rit.edu/gentoo/ https://mirror.sjc02.svwh.net/gentoo/ https://gentoo.ussg.indiana.edu/"
LANG="en_US.utf8"
LDFLAGS="-Wl,-O1,--hash-style=gnu,--sort-common,--as-needed"
MAKEOPTS="-j5"
PKGDIR="/usr/portage/packages"
PORTAGE_CONFIGROOT="/"
PORTAGE_RSYNC_OPTS="--recursive --links --safe-links --perms --times --omit-dir-times --compress --force --whole-file --delete --stats --human-readable --timeout=180 --exclude=/distfiles --exclude=/local --exclude=/packages --exclude=/.git"
PORTAGE_TMPDIR="/var/tmp"
SHELL="/bin/bash"
USE="7z X a52 aac acl acpi alsa amd64 apache2 apcupsd bip148 bitcoin_protocol_taproot branding bzip2 cairo cdda cddb cdr cli crypt cuda cups dbus dcaenc dmraid dri dts dvd dvdr egl elogind eme-free encode eselect-ldso exif f2fs fat fdk flac fontconfig fortran gd gdbm gif gmp-autoupdate gphoto2 gpm graphite gtk gui hddtemp http2 hwaccel iconv icu imlib ios javafx jfs jpeg jpeg2k lapack lcms libglvnd libinput libkms libnotify libtirpc libunwind lzma mad mdadm mmx mng mp3 mp4 mpeg mse multilib ncurses nls nptl nss ntfs nvenc nvidia offensive ogg opencl opengl openmp opus pam pango pcre pcre16 pdf plasma png policykit ppds profiler pulseaudio qt5 readline scanner sdl seccomp slit speex spell split-usr sqlite sse sse2 ssl startup-notification svg systray taglib theora tiff toolbar truetype udev udisks unicode upower usb v4l v4l2 vaapi vhosts video vim-syntax vorbis vpx webengine webp x264 x265 xa xattr xcb xfs xft xml xv xvid zip zlib" ABI_X86="64 32" ADA_TARGET="gnat_2020" APACHE2_MODULES="authn_core authz_core socache_shmcb unixd actions alias auth_basic authn_alias authn_anon authn_dbm authn_default authn_file authz_dbm authz_default authz_groupfile authz_host authz_owner authz_user autoindex cache cgi cgid dav dav_fs dav_lock deflate dir disk_cache env expires ext_filter file_cache filter headers include info log_config logio mem_cache mime mime_magic negotiation rewrite setenvif speling status unique_id userdir usertrack vhost_alias" CALLIGRA_FEATURES="karbon sheets words" COLLECTD_PLUGINS="df interface irq load memory rrdtool swap syslog" CPU_FLAGS_X86="aes avx avx2 f16c fma3 mmx mmxext pclmul popcnt sse sse2 sse3 sse4_1 sse4_2 ssse3" ELIBC="glibc" GPSD_PROTOCOLS="ashtech aivdm earthmate evermore fv18 garmin garmintxt gpsclock greis isync itrax mtk3301 nmea ntrip navcom oceanserver oldstyle oncore rtcm104v2 rtcm104v3 sirf skytraq superstar2 timing tsip tripmate tnt ublox ubx" INPUT_DEVICES="evdev synaptics" KERNEL="linux" LCD_DEVICES="bayrad cfontz cfontz633 glk hd44780 lb216 lcdm001 mtxorb ncurses text" LIBREOFFICE_EXTENSIONS="presenter-console presenter-minimizer" LLVM_TARGETS="NVPTX" LUA_SINGLE_TARGET="lua5-1" LUA_TARGETS="lua5-1" OFFICE_IMPLEMENTATION="libreoffice" PHP_TARGETS="php7-0 php7-1" POSTGRES_TARGETS="postgres12 postgres13" PYTHON_SINGLE_TARGET="python3_9" PYTHON_TARGETS="python3_10 python3_9" RUBY_TARGETS="ruby27 ruby30 ruby31" USERLAND="GNU" VIDEO_CARDS="fbdev nvidia v4l2 vesa vga" XTABLES_ADDONS="quota2 psd pknock lscan length2 ipv4options ipset ipp2p iface geoip fuzzy condition tee tarpit sysrq proto steal rawnat logmark ipmark dhcpmac delude chaos account"
Unset:  ADDR2LINE, AR, ARFLAGS, AS, ASFLAGS, CC, CCLD, CONFIG_SHELL, CPP, CPPFLAGS, CTARGET, CXX, CXXFILT, ELFEDIT, EMERGE_DEFAULT_OPTS, EXTRA_ECONF, F77FLAGS, FC, GCOV, GPROF, INSTALL_MASK, LC_ALL, LD, LEX, LFLAGS, LIBTOOL, LINGUAS, MAKE, MAKEFLAGS, NM, OBJCOPY, OBJDUMP, PORTAGE_BINHOST, PORTAGE_BUNZIP2_COMMAND, PORTAGE_COMPRESS, PORTAGE_COMPRESS_FLAGS, PORTAGE_RSYNC_EXTRA_OPTS, RANLIB, READELF, RUSTFLAGS, SIZE, STRINGS, STRIP, YACC, YFLAGS

**Comment by bobwya** [comment]
I've only been building this package against **SDL2**. I presume Upstream is doing the same!
**dhewm3** version **1.5.2_RC1** breaks compatibility with **SDL1** - as you discovered!

I've pushed a potential fix to the package. Could you sync my Overlay and re-test building the package?
If the game runs OK I'll suggest something similar to my (hacky) fix to the **dhewm3** developer - to maintain **SDL1** compatibility.

Thanks

**Comment by je-fro** [comment]
Looks like it's working - thanks!!
