### ISSUE TITLE
firefox-111.0 failed to build

### ISSUE THREAD

**Issue by J4ckTh3R1pper** [bobwya/bobwya#55]
>>> Emerging (2 of 2) www-client/firefox-111.0::bobwya
>>> Downloading 'http://distfiles.gentoo.org/distfiles/04/firefox-111-patches-01j.tar.xz'
--2023-04-25 19:15:00--  http://distfiles.gentoo.org/distfiles/04/firefox-111-patches-01j.tar.xz
Resolving distfiles.gentoo.org... 224.0.0.1
Connecting to distfiles.gentoo.org|224.0.0.1|:80... connected.
HTTP request sent, awaiting response... 404 Not Found
2023-04-25 19:15:02 ERROR 404: Not Found.

>>> Downloading 'https://dev.gentoo.org/~whissi/mozilla/patchsets/firefox-111-patches-01j.tar.xz'
--2023-04-25 19:15:02--  https://dev.gentoo.org/~whissi/mozilla/patchsets/firefox-111-patches-01j.tar.xz
Resolving dev.gentoo.org... 224.0.0.1
Connecting to dev.gentoo.org|224.0.0.1|:443... connected.
HTTP request sent, awaiting response... 404 Not Found
2023-04-25 19:15:02 ERROR 404: Not Found.

>>> Downloading 'https://dev.gentoo.org/~polynomial-c/mozilla/patchsets/firefox-111-patches-01j.tar.xz'
--2023-04-25 19:15:02--  https://dev.gentoo.org/~polynomial-c/mozilla/patchsets/firefox-111-patches-01j.tar.xz
Resolving dev.gentoo.org... 224.0.0.1
Connecting to dev.gentoo.org|224.0.0.1|:443... connected.
HTTP request sent, awaiting response... 404 Not Found
2023-04-25 19:15:03 ERROR 404: Not Found.

Looks like the patch file for Firefox 111 has been removed.

**Comment by bobwya** [comment]
Sorry for the hold-up fixing this!
