### ISSUE TITLE
sys-apps/tuxclocker Package Issues

### ISSUE THREAD

**Issue by ThisNekoGuy** [bobwya/bobwya#56]
Greetings,

Can you (at least) update sys-apps/tuxclocker-9999 to make the nvidia-driver toggle-able via USE flag?

I just switched from an Nvidia GPU, so... I no longer need their driver and honestly don't want it installed.
I would have installed the other ebuild, because that one does have the use flag, but it installs an outdated version of the package...

**Comment by bobwya** [comment]
@ThisNekoGuy 

Sorry this package was so neglected... Took a bit of work to get it up-to-date and working again!

I've tested locally with a system with an AMD CPU and an Nvidia GPU - and the most recent tuxclocker application release appears to work OK. Please open another issue if you find any problems, with the updated ebuilds.
