### ISSUE TITLE
Can't build firefox-kde-opensuse-49.0.1

### ISSUE THREAD

**Issue by eemantsal** [bobwya/bobwya#8]
I had no problem intalling the previous version, but in 49.0.1 I get this error:
` * ERROR: www-client/firefox-kde-opensuse-49.0.1::bobwya failed (prepare phase):`
` *   patch -p1  failed with /var/tmp/portage/www-client/firefox-kde-opensuse-49.0.1/work/firefox-kde-patchset/mozilla-gtk3_20.patch`
` * `
` * Call stack:`
` *               ebuild.sh, line  115:  Called src_prepare`
` *             environment, line 5653:  Called default`
` *      phase-functions.sh, line  805:  Called default_src_prepare`
` *      phase-functions.sh, line  870:  Called __eapi6_src_prepare`
` *             environment, line  617:  Called eapply '/var/tmp/portage/www-client/firefox-kde-opensuse-49.0.1/work/firefox' '/var/tmp/portage/www-client/firefox-kde-opensuse-49.0.1/work/firefox-kde-patchset/mozilla-kde.patch' '/var/tmp/portage/www-client/firefox-kde-opensuse-49.0.1/work/firefox-kde-patchset/mozilla-language.patch' '/var/tmp/portage/www-client/firefox-kde-opensuse-49.0.1/work/firefox-kde-patchset/mozilla-nongnome-proxies.patch' '/var/tmp/portage/www-client/firefox-kde-opensuse-49.0.1/work/firefox-kde-patchset/mozilla-gtk3_20.patch' '/var/tmp/portage/www-client/firefox-kde-opensuse-49.0.1/work/firefox-kde-patchset/firefox-branded-icons.patch' '/var/tmp/portage/www-client/firefox-kde-opensuse-49.0.1/work/firefox-kde-patchset/firefox-kde.patch' '/var/tmp/portage/www-client/firefox-kde-opensuse-49.0.1/work/firefox-kde-patchset/firefox-no-default-ualocale.patch' '/var/lib/layman/bobwya/www-client/firefox-kde-opensuse/files/firefox-kde-opensuse-48.0-pgo.patch'`
` *             environment, line 1675:  Called _eapply_patch '/var/tmp/portage/www-client/firefox-kde-opensuse-49.0.1/work/firefox-kde-patchset/mozilla-gtk3_20.patch'`
` *             environment, line 1613:  Called __helpers_die 'patch -p1  failed with /var/tmp/portage/www-client/firefox-kde-opensuse-49.0.1/work/firefox-kde-patchset/mozilla-gtk3_20.patch'`
` *   isolated-functions.sh, line  117:  Called die`
` * The specific snippet of code:`
` *              die "$@" `

I did install the version 49.0 without any issues with GTK3 nor anything else, as I said before. I didn't consciously change anything, but just in case, these are the flags I'm using:
`[ebuild     U ~] www-client/firefox-kde-opensuse-49.0.1::bobwya [49.0::bobwya] USE="dbus gmp-autoupdate hwaccel jemalloc jit kde skia -bindist -custom-cflags -custom-optimization -debug -gtk2 -hardened (-neon) -pgo -pulseaudio (-selinux) -startup-notification -system-cairo -system-harfbuzz -system-icu -system-jpeg -system-libevent -system-libvpx -system-sqlite {-test} -wifi" L10N="es-ES -ach -af -an -ar -as -ast -az -be -bg -bn-BD -bn-IN -br -bs -ca -cs -cy -da -de -el -en-GB -en-ZA -eo -es-AR -es-CL -es-MX -et -eu -fa -fi -fr -fy -ga -gd -gl -gu -he -hi -hr -hsb -hu -hy -id -is -it -ja -kk -km -kn -ko -lt -lv -mai -mk -ml -mr -ms -nb -nl -nn -or -pa -pl -pt-BR -pt-PT -rm -ro -ru -si -sk -sl -son -sq -sr -sv -ta -te -th -tr -uk -uz -vi -xh -zh-CN -zh-TW"`

If you need the complete build log or any other info, please don't hesitate to ask.

**Comment by bobwya** [comment]
Thanks for reporting the issue... I'd just been waiting for a tag for the firefox 49 branch from Wolfgang - which has now dropped (http://www.rosenauer.org/hg/mozilla/shortlog/fdfd88b0c2d7). I've pushed an update to the package including that.

Your issue should be fixed now!
