### ISSUE TITLE
firefox-kde-opensuse-50.0.ebuild and force qt patch issue

### ISSUE THREAD

**Issue by xprop** [bobwya/bobwya#9]
Hey, I can't build this with the force-qt-dialog patch. Everything was fine in 49.0.2.
It proceeds normally with the rest of the patches up until the qt patch.
Here is the emerge log - http://pastebin.com/53Yi346n

**Comment by bobwya** [comment]
Not sure why you want to have **firefox-kde-opensuse-kde-debug.patch** enabled all the time... I wouldn't recommend that!!
But the "customer knows best"... So I've tweaked the 2 custom patches to allow them to be applied simultaneously... :-) You'll have to sync to pull the package changes.
